eureka:
  client:
    service-url:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-teritary:8013/eureka/
#---
#spring:
#  profiles: lucky-word
wordConfig:
  preamble: the lukyword is 
  luckyWord: newone.
---
spring:
  profiles: subject
  application:
    name: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: article
words: a,the

---
spring:
  profiles: adjective
  application:
    name: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog